name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            TARGET_DIR="/var/www/hrmdaddy"
            echo "Setting up target directory: $TARGET_DIR"
            sudo mkdir -p $TARGET_DIR
            echo "Changing ownership of $TARGET_DIR to $USER"
            sudo chown -R $USER:$USER $TARGET_DIR
            echo "Setting permissions for $TARGET_DIR"
            sudo chmod -R 775 $TARGET_DIR
            cd $TARGET_DIR
            echo "Current directory: $(pwd)"
            if [ ! -d .git ]; then
              echo "Cloning repository into $TARGET_DIR"
              git clone https://github.com/your-repo/hrmdaddy.git .
            fi
            echo "Resetting and pulling latest changes"
            git reset --hard origin/main
            git pull origin main
            echo "Restarting Apache"
            sudo systemctl restart apache2
