name: Deploy Laravel

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Private Key
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          cat private_key.pem

      - name: Add SSH Key to Agent
        run: |
          eval $(ssh-agent -s)
          ssh-add private_key.pem

      - name: Deploy to EC2
        env:
          HOST: ec2-52-66-102-73.ap-south-1.compute.amazonaws.com
        run: |
          ssh -v -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$HOST << 'EOF'
            cd /var/www/hrmdaddy/hrmd_live
            git status
            git fetch --all
            git reset --hard origin/main
            git status
            composer install --no-dev
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:cache
            sudo chown -R nginx:nginx storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            sudo chmod -R 777 storage bootstrap/cache
            sudo systemctl restart nginx php-fpm
          EOF
