name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full commit history

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            TARGET_DIR="/var/www/hrmdaddy"
            echo "Deploying to $TARGET_DIR"
            cd $TARGET_DIR
            
            # Ensure correct branch
            git fetch origin
            git checkout main || git checkout -b main origin/main
            git reset --hard origin/main
            git clean -fd
            git pull origin main

            # Install dependencies if package.json changes
            if git diff --name-only HEAD@{1} HEAD | grep -q "package.json"; then
              echo "package.json changed, installing dependencies..."
              npm install --production
            else
              echo "No changes in package.json, skipping npm install."
            fi
            
            # Set correct Laravel permissions
            sudo chown -R www-data:www-data $TARGET_DIR
            sudo chmod -R 775 storage bootstrap/cache
            
            # Run Laravel migrations
            php artisan migrate --force
            
            # Clear caches
            php artisan cache:clear
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:clear
            php artisan optimize:clear  # NEW: Ensures Laravel reloads everything
            
            # Restart Apache
            sudo systemctl reload apache2
