name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html
            
            # Pull latest changes if repo exists, else clone it
            if [ -d ".git" ]; then
              git reset --hard origin/main
              git pull origin main
            else
              git clone --depth 1 --branch main git@github.com:your-repo.git /var/www/html
            fi
            
            # Install dependencies only if package.json has changed
            if [ -f package.json ]; then
              if [ "$(git diff --name-only HEAD@{1} package.json)" ]; then
                npm install --production
              fi
            fi

            # Set correct permissions (only if needed)
            sudo find storage bootstrap/cache -type d -exec chmod 775 {} \;
            sudo find storage bootstrap/cache -type f -exec chmod 664 {} \;
            sudo chown -R www-data:www-data storage bootstrap/cache

            # Restart Apache only if needed
            sudo systemctl reload apache2
