name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Define deployment directory
            TARGET_DIR="/var/www/hrmdaddy"
            echo "Deploying to $TARGET_DIR"
            # Navigate to the existing directory
            cd $TARGET_DIR
            # Ensure correct permissions before pulling
            sudo chown -R $USER:$USER $TARGET_DIR
            sudo chmod -R 755 $TARGET_DIR
            # Pull latest changes if repo exists, else initialize git
            if [ -d ".git" ]; then
              echo "Git repository found. Pulling latest changes..."
              git reset --hard origin/main
              git pull origin main
            else
              echo "No repository found! Initializing repository..."
              git init
              git remote add origin git@github.com:your-repo.git
              git fetch origin
              git checkout -t origin/main
            fi
            # Install dependencies only if package.json has changed
            if [ -f package.json ]; then
              if git diff --quiet HEAD@{1} HEAD -- package.json; then
                echo "package.json changed, installing dependencies..."
                npm install --production
              else
                echo "No changes in package.json, skipping npm install."
              fi
            fi
            # Set correct Laravel permissions
            sudo find storage bootstrap/cache -type d -exec chmod 775 {} \;
            sudo find storage bootstrap/cache -type f -exec chmod 664 {} \;
            sudo chown -R www-data:www-data storage bootstrap/cache
            # Run Laravel migrations (optional)
            php artisan migrate --force
            # Clear caches to reflect changes
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            # Restart Apache to apply changes
            sudo systemctl reload apache2
