name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/hrmdaddy
            cd ~/hrmdaddy
            if [ ! -d .git ]; then
              git clone https://github.com/your-repo/hrmdaddy.git .
            fi
            git reset --hard origin/main
            git pull origin main
            sudo systemctl restart apache2
